### ISSUE TITLE
Option for Setting First day of the week on Monday 

### ISSUE THREAD

**Issue by aein** [w11k/calendar-for-trello#157] opened 2017-04-18 22:12 UTC
Would love to have the option for setting the first day of the week starting on Monday instead of Sunday.

**Comment by fvonberg** [comment] 2017-06-01 16:06
Todo:
* add Settings Feature
* use 'isoWeek' in moment.js
* change order of the cards
* check drag'n'drop

**Comment by jblankenhorn** [comment] 2017-06-02 06:11
@fvonberg this is currently done automatically by selecting the language.

**Comment by skymaster420** [comment] 2017-09-21 09:32
Not sure why this is marked as closed.
Selecting the date does indeed change the start date but also changes the language.  Its now more common internationally for the start of the week to be Monday however the English language sets this as Sunday.  Could this be change? or as @aein states an option in the setting would be nice.

**Comment by jblankenhorn** [comment] 2017-09-21 09:33
@skymaster420 it is a duplicate of Ticket #176

**Closed by jblankenhorn** 2017-09-21 09:33 UTC
Labels: enhancement
