### ISSUE TITLE
configure Calendar's First day of Week

### ISSUE THREAD

**Issue by vcakarov** [w11k/calendar-for-trello#132] opened 2017-01-27 12:55 UTC
I cannot find configuration for first day of week. By default it is Sunday, but I need it Monday, for example. 
If it is not possible, I suggest to add this feature (independent on the Language setting, I still want UI localized in English language).

**Comment by jblankenhorn** [comment] 2017-11-10 13:20
duplicate of #176

**Closed by jblankenhorn** 2017-11-10 13:20 UTC
Labels: duplicate, enhancement
