### ISSUE TITLE
Can't delete tasks from closed or moved boards

### ISSUE THREAD

**Issue by valerierupp** [w11k/calendar-for-trello#178] opened 2017-07-19 19:38 UTC
Tasks that are were assigned to a board and later moved show duplicate listings. When I click on the task I'd like to remove it brings me to a screen that says the board no longer exists. (below)

"Card not found.

This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams."

**Comment by jblankenhorn** [comment] 2017-10-27 12:31
I believe this is a duplicate of #173

**Closed by jblankenhorn** 2017-10-27 12:31 UTC
Labels: bug
