### ISSUE TITLE
Link click opens card in new tab briefly, then tab closes (Chrome)

### ISSUE THREAD

**Issue by ColonelAngus** [w11k/calendar-for-trello#74] opened 2016-09-21 05:23 UTC
Only in Chrome. I haven't seen this happen before today. I've refreshed, cleared cache, log in/out. 
Working fine in Firefox.

**Comment by CanKattwinkel** [comment] 2016-10-17 19:52
Hello @ColonelAngus,
I couldn't reproduce your issue. I'll close this for now since we are already working on Trello Calendar v2.
The Calendar will be replaced very soon.

**Closed by CanKattwinkel** 2016-10-17 19:52 UTC
