### ISSUE TITLE
Week and day view

### ISSUE THREAD

**Issue by SMukta** [w11k/calendar-for-trello#76] opened 2016-09-30 17:00 UTC
First- thumbs up for the app! wonderful!
I would like to request you to add week and day views. It will help the workflow greatly.
Thank you!

**Comment by CanKattwinkel** [comment] 2016-10-04 08:24
Hello thanks for the feedback!

This is actually a duplicate of https://github.com/w11k/calendar-for-trello/issues/58

I'll close this issue. The feature will definitively be implemented soon.

**Closed by CanKattwinkel** 2016-10-04 08:24 UTC
Labels: enhancement

**Comment by SMukta** [comment] 2016-10-07 21:41
Wonderful. Thank you!
